export const PRODUCT_LIST_REQUEST = 'RODUCT_LIST_REQUEST';
export const PRODUCT_LIST_SUCCESS = 'RODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_FAIL = 'RODUCT_LIST_FAIL';

export const PRODUCT_DETAILS_REQUEST = 'RODUCT_DETAILS_REQUEST';
export const PRODUCT_DETAILS_SUCCESS = 'RODUCT_DETAILS_SUCCESS';
export const PRODUCT_DETAILS_FAIL = 'RODUCT_DETAILS_FAIL';

export const PRODUCT_SAVE_REQUEST = 'RODUCT_SAVE_REQUEST';
export const PRODUCT_SAVE_SUCCESS = 'RODUCT_SAVE_SUCCESS';
export const PRODUCT_SAVE_FAIL = 'RODUCT_SAVE_FAIL';

export const PRODUCT_DELETE_REQUEST = 'RODUCT_DELETE_REQUEST';
export const PRODUCT_DELETE_SUCCESS = 'RODUCT_DELETE_SUCCESS';
export const PRODUCT_DELETE_FAIL = 'RODUCT_DELETE_FAIL';